version: '3.8'
services:
  frontend:
    build: ./international-weather-frontend
    ports:
      - ${FRONTEND_PORT_OUTSIDE}:${FRONTEND_PORT_INSIDE}
    environment:
      - PORT=${FRONTEND_PORT_INSIDE}
      - API_PROTOCOL="http:"
      - API_HOST="localhost"
      - API_PORT=${BACKEND_PORT_OUTSIDE}
      - API_MAX_REQUEST_TIMEOUT=30000
  backend:
    build: ./international-weather-backend
    ports:
      - ${BACKEND_PORT_OUTSIDE}:${BACKEND_PORT_INSIDE}
    environment:
      - PORT=${BACKEND_PORT_INSIDE}
      - WEATHER_API_KEY="api_key"
